# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proxy_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProxDlg(object):
    def setupUi(self, ProxDlg):
        ProxDlg.setObjectName("ProxDlg")
        ProxDlg.resize(400, 253)
        self.groupBox = QtWidgets.QGroupBox(ProxDlg)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 361, 231))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 60, 91, 16))
        self.label.setObjectName("label")
        self.radio_http = QtWidgets.QRadioButton(self.groupBox)
        self.radio_http.setGeometry(QtCore.QRect(140, 60, 71, 20))
        self.radio_http.setObjectName("radio_http")
        self.radio_socks = QtWidgets.QRadioButton(self.groupBox)
        self.radio_socks.setGeometry(QtCore.QRect(230, 60, 71, 20))
        self.radio_socks.setObjectName("radio_socks")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.edt_ipaddr = QtWidgets.QTextEdit(self.groupBox)
        self.edt_ipaddr.setGeometry(QtCore.QRect(140, 100, 191, 21))
        self.edt_ipaddr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.edt_ipaddr.setObjectName("edt_ipaddr")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 81, 16))
        self.label_3.setObjectName("label_3")
        self.edt_puerto = QtWidgets.QTextEdit(self.groupBox)
        self.edt_puerto.setGeometry(QtCore.QRect(140, 140, 191, 21))
        self.edt_puerto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.edt_puerto.setObjectName("edt_puerto")
        self.btn_prueba = QtWidgets.QPushButton(self.groupBox)
        self.btn_prueba.setGeometry(QtCore.QRect(40, 190, 75, 24))
        self.btn_prueba.setObjectName("btn_prueba")
        self.btn_ok = QtWidgets.QPushButton(self.groupBox)
        self.btn_ok.setGeometry(QtCore.QRect(150, 190, 75, 24))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(self.groupBox)
        self.btn_cancel.setGeometry(QtCore.QRect(260, 190, 75, 24))
        self.btn_cancel.setObjectName("btn_cancel")
        self.checo_habil = QtWidgets.QCheckBox(self.groupBox)
        self.checo_habil.setGeometry(QtCore.QRect(40, 30, 141, 20))
        self.checo_habil.setObjectName("checo_habil")

        self.retranslateUi(ProxDlg)
        QtCore.QMetaObject.connectSlotsByName(ProxDlg)

    def retranslateUi(self, ProxDlg):
        _translate = QtCore.QCoreApplication.translate
        ProxDlg.setWindowTitle(_translate("ProxDlg", "Dialog"))
        self.groupBox.setTitle(_translate("ProxDlg", "Settings"))
        self.label.setText(_translate("ProxDlg", "Proxy Protocol:"))
        self.radio_http.setText(_translate("ProxDlg", "HTTP(S)"))
        self.radio_socks.setText(_translate("ProxDlg", "SOCKS5"))
        self.label_2.setText(_translate("ProxDlg", "Hostname/IP:"))
        self.label_3.setText(_translate("ProxDlg", "Port:"))
        self.btn_prueba.setText(_translate("ProxDlg", "Test"))
        self.btn_ok.setText(_translate("ProxDlg", "Save"))
        self.btn_cancel.setText(_translate("ProxDlg", "Cancel"))
        self.checo_habil.setText(_translate("ProxDlg", "Enable Proxy"))
